### ISSUE TITLE
Error: java.lang.NullPointerException

### ISSUE THREAD

**Issue by echoaiya** [sonyxperiadev/MultimediaForAndroidLibrary#3]
When I played "http://www.digitalprimates.net/dash/streams/gpac/mp4-main-multi-mpd-AV-NBS.mpd" with MultimediaForAndroidLibrary, I got this:

---------------------------------------------------------------------------------------------------------------------------
05-12 13:54:57.932: E/AndroidRuntime(18739): FATAL EXCEPTION: DASH
05-12 13:54:57.932: E/AndroidRuntime(18739): Process: com.sonymobile.android.media.testmediaplayer, PID: 18739
05-12 13:54:57.932: E/AndroidRuntime(18739): java.lang.NullPointerException
05-12 13:54:57.932: E/AndroidRuntime(18739): 	at com.sonymobile.android.media.internal.mpegdash.MPDParser.endRepresentation(MPDParser.java:510)
05-12 13:54:57.932: E/AndroidRuntime(18739): 	at com.sonymobile.android.media.internal.mpegdash.MPDParser.parse(MPDParser.java:172)
05-12 13:54:57.932: E/AndroidRuntime(18739): 	at com.sonymobile.android.media.internal.mpegdash.DASHSession.onConnect(DASHSession.java:391)
05-12 13:54:57.932: E/AndroidRuntime(18739): 	at com.sonymobile.android.media.internal.mpegdash.DASHSession.access$0(DASHSession.java:368)
05-12 13:54:57.932: E/AndroidRuntime(18739): 	at com.sonymobile.android.media.internal.mpegdash.DASHSession$EventHandler.handleMessage(DASHSession.java:241)
05-12 13:54:57.932: E/AndroidRuntime(18739): 	at android.os.Handler.dispatchMessage(Handler.java:110)
05-12 13:54:57.932: E/AndroidRuntime(18739): 	at android.os.Looper.loop(Looper.java:193)
05-12 13:54:57.932: E/AndroidRuntime(18739): 	at 
android.os.HandlerThread.run(HandlerThread.java:61)

-------------------------------------------------------------------------------------------------------------------------------

I guess it's because the dash server and mpd parser. I want to build dash server, but I only find mp4box. What is your dash server?
I can played the mpd of "res/raw/sourcefile". 
Can you tell me what is the difference between the "gpac-mpd" and the "sourcefile-mpd"?

**Comment by JimmyDahlqvist** [comment]
Hi.
Thank you for your comment.

We investigated your mpd-file an it contains a legacy representation list, the library do not support that.
However the library should not crash, we will investigate and fix that in a later release.

Regards
Jimmy

**Comment by JimmyDahlqvist** [comment]
I reopen the issue, we will fix the crash for the unsupported mpd file. A solution exists on our internal development branch and will be uploaded soon. I will close the issue again when merged.
