### ISSUE TITLE
Error: media.MediaCodec.releaseOutputBuffer(Native Method)

### ISSUE THREAD

**Issue by echoaiya** [sonyxperiadev/MultimediaForAndroidLibrary#4]
I always got this error when I played default mpd with the latest version:

-------------------------------------------------------------------------------------------------------------------------------
05-12 14:21:44.224: E/VideoThread(19094): Codec error: Window(Surface) valid: true
05-12 14:21:44.224: E/VideoThread(19094): java.lang.IllegalStateException
05-12 14:21:44.224: E/VideoThread(19094): 	at android.media.MediaCodec.releaseOutputBuffer(Native Method)
05-12 14:21:44.224: E/VideoThread(19094): 	at com.sonymobile.android.media.internal.VideoThread.doRender(VideoThread.java:792)
05-12 14:21:44.224: E/VideoThread(19094): 	at com.sonymobile.android.media.internal.VideoThread.access$11(VideoThread.java:729)
05-12 14:21:44.224: E/VideoThread(19094): 	at com.sonymobile.android.media.internal.VideoThread$RenderingHandler.handleMessage(VideoThread.java:951)
05-12 14:21:44.224: E/VideoThread(19094): 	at android.os.Handler.dispatchMessage(Handler.java:110)
05-12 14:21:44.224: E/VideoThread(19094): 	at android.os.Looper.loop(Looper.java:193)
05-12 14:21:44.224: E/VideoThread(19094): 	at android.os.HandlerThread.run(HandlerThread.java:61)
05-12 14:21:44.225: E/Player(19094): Codec Error occurred!
05-12 14:21:44.361: E/ACodec(19094): [OMX.MTK.VIDEO.DECODER.AVC] storeMetaDataInBuffers failed w/ err 80000000

-------------------------------------------------------------------------------------------------------------------------------

**Comment by JimmyDahlqvist** [comment]
Hi.

Can you share phone model and Android version?

Regards
Jimmy

**Comment by echoaiya** [comment]
Thanks for your response. 
My phone is Android 4.4.2(MTK6582). Model number is Sky 6.0Q.
